version: '2'
services:
  spark:
    image: mini-spark/spark:${SPARK_VERSION}
    depends_on:
      - openioci
  openioci:
    image: openioci/runtime
    networks:
      default:
        ipv4_address: 172.25.0.2

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
